// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu8SFDxO0JNd3wXIsxX797W3tuNvyKnCk',
    appId: '1:1071510691550:web:f89933fc9582f0ab6fec4f',
    messagingSenderId: '1071510691550',
    projectId: 'gmp-glossary',
    authDomain: 'gmp-glossary.firebaseapp.com',
    storageBucket: 'gmp-glossary.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPRQsX24LxReBh0PgFZ-xVf9-nsl0w59o',
    appId: '1:1071510691550:android:4003260102203f506fec4f',
    messagingSenderId: '1071510691550',
    projectId: 'gmp-glossary',
    storageBucket: 'gmp-glossary.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc_Ov21dngwAnKN6RE9sFI_d8SK7PCQrY',
    appId: '1:1071510691550:ios:c6f06a17e996937c6fec4f',
    messagingSenderId: '1071510691550',
    projectId: 'gmp-glossary',
    storageBucket: 'gmp-glossary.appspot.com',
    iosClientId: '1071510691550-a46nfv6jakvehmc4g5eq53rhk6gfha9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectGlossary',
  );
}
